=== Synaps33/FroggyKVM/pspkvm/jsr135/src/config/javacall/configuration.dtd
<!--
        	
        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<!ELEMENT configuration (properties | constants)+>
<!ELEMENT properties (property)+>
<!ELEMENT property EMPTY>
<!-- If callout is specified, it must be a defined native function -->
<!--  with the signature: char* foo(void) -->
<!ATTLIST property
        Key      CDATA                          #REQUIRED
        Value    CDATA                          #REQUIRED
        Scope    (system | internal)            "internal"
        Callout  CDATA                          #IMPLIED
        Comment  CDATA                          #IMPLIED
>
<!ELEMENT constants (constant_class)+>
<!ELEMENT constant_class (constant)+>
<!ATTLIST constant_class
    Package  CDATA                          #REQUIRED
    Name     CDATA                          #REQUIRED
    Scope    (protected | public)           "public"
    Comment  CDATA                          #IMPLIED
>

<!ELEMENT constant EMPTY>
<!ATTLIST constant
    Type     (int | String | boolean)       #IMPLIED
    Name     CDATA                          #REQUIRED
    Value    CDATA                          #REQUIRED
    VScope   (protected | public | private) #REQUIRED
    Comment  CDATA                          #IMPLIED
>

=== Synaps33/FroggyKVM/pspkvm/jsr120/build/share/config/properties_jsr120.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
    
  
  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.
  
-->
<!-- System-independent JSR 205 properties required by the specification -->
<configuration>
  <properties>
    <!-- SYSTEM PROPERTIES -->
    <!-- Visible from System.getProperty() -->

    <property Key="wireless.messaging.version"
      Value="1.1"
      Scope="system"
      Comment="WMA version number."/>

    <property Key="wireless.messaging.sms.smsc"
      Value="+17815511212"
      Scope="system"
      Comment="Default SMS Service Center address."/>
    
    <!-- INTERNAL PROPERTIES -->
    <!-- Visible from Configuration.getProperty() -->
    <property Key="com.sun.midp.io.j2me.wma.DatagramHost"
      Value="wmadatagramhost"
      Comment="The datagram host name for wma emulated messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.DatagramPortIn"
      Value="11100"
      Scope="internal"
      Comment="The datagram port number for inbound SMS messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.DatagramPortOut"
      Value="11101"
      Scope="internal"
      Comment="The datagram port number of outbound SMS messages."/>
    
    <property Key="com.sun.midp.io.j2me.cbs.DatagramPortIn"
      Value="22200"
      Scope="internal"
      Comment="The datagram port number for inbound CBS messages."/>
    
    <property Key="com.sun.midp.io.j2me.sms.PhoneNumber"
      Value="+5551212"
      Scope="internal"
      Comment="The phone number for outbound messages from the SMS emulator."/>
    
  </properties>
</configuration>

=== Synaps33/FroggyKVM/pspkvm/jsr135/src/config/javacall/properties_jsr135.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "configuration.dtd">
<!--
        Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
        DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
        
        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License version
        2 only, as published by the Free Software Foundation.
        
        This program is distributed in the hope that it will be useful, but
        WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
        General Public License version 2 for more details (a copy is
        included at /legal/license.txt).
        
        You should have received a copy of the GNU General Public License
        version 2 along with this work; if not, write to the Free Software
        Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
        02110-1301 USA
        
        Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
        Clara, CA 95054 or visit www.sun.com if you need additional
        information or have any questions.
-->
<!-- MMAPI PROPERTIES required by the specification -->
<configuration>
<properties>
<!-- SYSTEM PROPERTIES -->
<!-- Visible from System.getProperty() -->
    <!-- JSR135(MMAPI) PROPERTIES -->
    <property Key="microedition.media.version"
      Value="1.1"
      Scope="system"
      Comment="Version number."/>

    <property Key="supports.mixing"
      Value=""
      Scope="system"
      Callout="get_system_property_supports_mixing" 
      Comment="Mixing support."/>

    <property Key="supports.audio.capture"
      Value="true"
      Scope="system"
      Comment="Audio capture support."/>

    <property Key="supports.video.capture"
      Value="false"
      Scope="system"
      Comment="Video capture support."/>

    <property Key="supports.recording"
      Value="true"
      Scope="system"
      Comment="Recording support."/>

    <property Key="audio.encodings" 
      Value="encoding=pcm" 
	  Scope="system"/>

    <!--
    <property Key="audio.encodings"
      Value="encoding=pcm encoding=pcm&amp;rate=8000&amp;bits=8&amp;channels=1 encoding=pcm&amp;rate=22050&amp;bits=16&amp;channels=2"
      Scope="system"
      Comment="Supported audio encodings."/>

    <property Key="video.encodings"
      Value="encoding=png"
      Scope="system"
      Comment="Supported video encodings."/>
    -->

    <!--
    <property Key="video.encodings"
      Value="encoding=rgb565&amp;width=160&amp;height=120 encoding=rgb565&amp;width=320&amp;height=240 encoding=rgb565&amp;width=120&amp;height=160"
      Scope="system"
      Comment="Supported video encodings."/>
    -->

    <property Key="video.snapshot.encodings"
      Value=""
      Scope="system"
      Comment="Supported video snapshot encodings."/>

    <!--
    <property Key="video.snapshot.encodings"
      Value="encoding=jpeg encoding=png"
      Scope="system"
      Comment="Supported video snapshot encodings."/>
    -->

    <!--
    <property Key="streamable.contents"
      Value="audio/x-wav"
      Scope="system"
      Comment="Streamable contents."/>
    -->

</properties>
</configuration>

=== Synaps33/FroggyKVM/pspkvm/jsr75/src/config/win32/properties_jsr75.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "../common/configuration.dtd">
<!--
   

  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.

-->
<!-- System-specific JSR 75 properties required by the specification -->
<configuration>
<properties>
<!-- System  properties (visible via System.getProperty() -->
  <property Key="fileconn.dir.private"
      Value="file:///Private/"
      Scope="system"
      Comment="The private work directory for MIDlet suite."/>

  <property Key="file.separator"
      Value="\\"
      Scope="system"
      Comment="The file separator character(s) for the underlying platform."/>

<!-- Internal properties (visible via Configuration.getProperty() -->
  <property Key="PIMRootDir"
      Value="file:///PIMdb/"
      Scope="internal"
      Comment="The root directory that contains PIM data."/>

  <property Key="DefaultContactList"
      Value="Default_contact"
      Scope="internal"
      Comment="The directory name of the default contact list."/>
		    
  <property Key="DefaultEventList"
      Value="Default_event"
      Scope="internal"
      Comment="The directory name of the default event list."/>
				
  <property Key="DefaultTodoList"
      Value="Default_todo"
      Scope="internal"
      Comment="The directory name of the default todo list."/>							    

  <property Key="file.linebreak"
      Value="\r\n"
      Scope="internal"
      Comment="The which terminates a line in text files."/>
</properties>
</configuration>

=== Synaps33/FroggyKVM/pspkvm/jsr75/src/config/javacall/properties_jsr75.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="html.xsl"?>
<!DOCTYPE configuration SYSTEM "../common/configuration.dtd">
<!--
  
  Copyright  1990-2007 Sun Microsystems, Inc. All Rights Reserved.
  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER
  
  This program is free software; you can redistribute it and/or
  modify it under the terms of the GNU General Public License version
  2 only, as published by the Free Software Foundation.
  
  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License version 2 for more details (a copy is
  included at /legal/license.txt).
  
  You should have received a copy of the GNU General Public License
  version 2 along with this work; if not, write to the Free Software
  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
  02110-1301 USA
  
  Please contact Sun Microsystems, Inc., 4150 Network Circle, Santa
  Clara, CA 95054 or visit www.sun.com if you need additional
  information or have any questions.
  
-->
<!-- System-independent JSR 75 properties required by the specification -->
<configuration>
<properties>
<!-- System  properties (visible via System.getProperty() -->
  <property Key="file.separator"
      Value=""
      Scope="system"
      Callout="getFileSeparator"
      Comment="The file separator character(s) for the underlying platform."/>

  <property Key="fileconn.dir.photos"
      Value=""
      Scope="system"
      Callout="getPhotosDir"
      Comment="The directory for photos and other images."/>

  <property Key="fileconn.dir.videos"
      Value=""
      Scope="system"
      Callout="getVideosDir"
      Comment="The directory for video clips."/>

  <property Key="fileconn.dir.graphics"
      Value=""
      Scope="system"
      Callout="getGraphicsDir"
      Comment="The directory for clip art graphics."/>

  <property Key="fileconn.dir.tones"
      Value=""
      Scope="system"
      Callout="getTonesDir"
      Comment="The directory for ring tones and other audio files."/>

  <property Key="fileconn.dir.music"
      Value=""
      Scope="system"
      Callout="getMusicDir"
      Comment="The directory for music."/>

  <property Key="fileconn.dir.recordings"
      Value=""
      Scope="system"
      Callout="getRecordingsDir"
      Comment="The directory for voice recordings."/>

  <property Key="fileconn.dir.private"
      Value=""
      Scope="system"
      Callout="getPrivateDir"
      Comment="The private work directory for MIDlet suite."/>

  <property Key="fileconn.dir.photos.name"
      Value=""
      Scope="system"
      Callout="getLocalizedPhotosDir"
      Comment="The localized name of photos and other images directory."/>

  <property Key="fileconn.dir.videos.name"
      Value=""
      Scope="system"
      Callout="getLocalizedVideosDir"
      Comment="The localized name of video clips directory."/>

  <property Key="fileconn.dir.graphics.name"
      Value=""
      Scope="system"
      Callout="getLocalizedGraphicsDir"
      Comment="The localized name of clip art graphics directory."/>

  <property Key="fileconn.dir.tones.name"
      Value=""
      Scope="system"
      Callout="getLocalizedTonesDir"
      Comment="The localized name of ring tones and other audio files directory."/>

  <property Key="fileconn.dir.music.name"
      Value=""
      Scope="system"
      Callout="getLocalizedMusicDir"
      Comment="The localized name of music directory."/>

  <property Key="fileconn.dir.recordings.name"
      Value=""
      Scope="system"
      Callout="getLocalizedRecordingsDir"
      Comment="The localized name of voice recordings directory."/>

  <property Key="fileconn.dir.private.name"
      Value=""
      Scope="system"
      Callout="getLocalizedPrivateDir"
      Comment="The localized name of private directory for MIDlet suite."/>

<!-- Internal properties (visible via Configuration.getProperty() -->
  <property Key="PIMRootDir"
      Value="file:///C:/"
      Scope="internal"
      Comment="The root directory that contains PIM data."/>
      
  <property Key="DefaultContactList"
      Value=""
      Scope="internal"
      Comment="The directory name of the default contact list."/> 

  <property Key="DefaultEventList"
      Value=""
      Scope="internal"
      Comment="The directory name of the default event list."/> 

  <property Key="DefaultTodoList"
      Value=""
      Scope="internal"
      Comment="The directory name of the default todo list."/> 

  <property Key="file.linebreak"
      Value="\r\n"
      Scope="internal"
      Comment="The which terminates a line in text files."/>
</properties>
</configuration>
